//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarvis.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SettingsVersion : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsVersion defaultInstance = ((SettingsVersion)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsVersion())));
        
        public static SettingsVersion Default {
            get {
                return defaultInstance;
            }
        }
    }
}
